# Generated by Django 4.2.6 on 2023-11-05 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("avatar", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AC", "Active"),
                            ("DS", "Disable"),
                            ("CN", "Cancelled"),
                        ],
                        default="AC",
                        max_length=20,
                    ),
                ),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "target_ct",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profiles",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-user"],
                "indexes": [
                    models.Index(
                        fields=["-user"], name="account_pro_user_id_251fe9_idx"
                    ),
                    models.Index(
                        fields=["target_ct", "target_id"],
                        name="account_pro_target__800225_idx",
                    ),
                ],
            },
        ),
    ]
