# Generated by Django 4.2.6 on 2023-11-06 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profile',
            name='account_pro_target__800225_idx',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='target_ct',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='target_id',
        ),
    ]
