# Generated by Django 4.2.6 on 2023-11-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amyx_bank", "0010_remove_bankaccount_user_remove_card_account_and_more"),
        ("account", "0003_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="accounts",
            field=models.ManyToManyField(
                related_name="bank_accounts", to="amyx_bank.bankaccount"
            ),
        ),
    ]
