# Generated by Django 4.2.6 on 2023-11-09 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("avatar", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AC", "Active"),
                            ("DS", "Disable"),
                            ("CN", "Cancelled"),
                        ],
                        default="AC",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-user"],
                "indexes": [
                    models.Index(
                        fields=["-user"], name="amyx_bank_p_user_id_129130_idx"
                    )
                ],
            },
        ),
    ]
