# Generated by Django 4.2.6 on 2023-11-05 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_name", models.CharField(default=None, max_length=50)),
                (
                    "card_account_code",
                    models.CharField(blank=True, default="C5-0001", max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AC", "Active"),
                            ("DS", "Disable"),
                            ("CN", "Cancelled"),
                        ],
                        default="AC",
                        max_length=20,
                    ),
                ),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "target_ct",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cards",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-card_account_code"],
                "indexes": [
                    models.Index(
                        fields=["-card_account_code"],
                        name="amyx_bank_c_card_ac_71e9ed_idx",
                    ),
                    models.Index(
                        fields=["target_ct", "target_id"],
                        name="amyx_bank_c_target__88d38b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=50)),
                (
                    "account_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "account_code",
                    models.CharField(blank=True, default="A5-0001", max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AC", "Active"),
                            ("DS", "Disable"),
                            ("CN", "Cancelled"),
                        ],
                        default="AC",
                        max_length=20,
                    ),
                ),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "target_ct",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_accounts",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-account_code"],
                "indexes": [
                    models.Index(
                        fields=["-account_code"], name="amyx_bank_b_account_21d153_idx"
                    ),
                    models.Index(
                        fields=["target_ct", "target_id"],
                        name="amyx_bank_b_target__9d7ea8_idx",
                    ),
                ],
            },
        ),
    ]
