# Generated by Django 4.2.6 on 2023-11-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amyx_bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bankaccount',
            name='amyx_bank_b_target__9d7ea8_idx',
        ),
        migrations.RemoveIndex(
            model_name='card',
            name='amyx_bank_c_target__88d38b_idx',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='target_ct',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='target_ct',
            new_name='account',
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['profile', 'target_id'], name='amyx_bank_b_profile_be2855_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['account', 'target_id'], name='amyx_bank_c_account_c7ec04_idx'),
        ),
    ]
