# Generated by Django 4.2.6 on 2023-10-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amyx_bank", "0003_bankaccount_card_remove_profile_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="account_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="status",
            field=models.CharField(
                choices=[("AC", "Active"), ("DS", "Disable"), ("CN", "Cancelled")],
                default="AC",
                max_length=20,
            ),
        ),
    ]
