# Generated by Django 4.2.6 on 2023-11-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amyx_bank', '0003_remove_bankaccount_amyx_bank_b_profile_be2855_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bankaccount',
            name='amyx_bank_b_target__9d7ea8_idx',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='target_ct',
            new_name='profile',
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['profile', 'target_id'], name='amyx_bank_b_profile_be2855_idx'),
        ),
    ]
