# Generated by Django 4.2.6 on 2023-11-06 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_remove_profile_account_pro_target__800225_idx_and_more'),
        ('amyx_bank', '0004_remove_bankaccount_amyx_bank_b_target__9d7ea8_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bankaccount',
            name='amyx_bank_b_profile_be2855_idx',
        ),
        migrations.RemoveIndex(
            model_name='card',
            name='amyx_bank_c_account_c7ec04_idx',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='target_id',
        ),
        migrations.RemoveField(
            model_name='card',
            name='target_id',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
        migrations.AlterField(
            model_name='card',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='amyx_bank.bankaccount'),
        ),
    ]
