# Generated by Django 4.2.6 on 2023-10-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amyx_bank', '0004_bankaccount_account_balance_bankaccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
