# Generated by Django 4.2.6 on 2023-10-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amyx_bank", "0005_bankaccount_account_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account_code",
            field=models.CharField(blank=True, default="A5-0001", max_length=20),
        ),
    ]
