# Generated by Django 4.2.6 on 2023-11-06 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_remove_profile_account_pro_target__800225_idx_and_more"),
        (
            "amyx_bank",
            "0005_remove_bankaccount_amyx_bank_b_profile_be2855_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bank_accounts",
                to="account.profile",
            ),
        ),
    ]
