# Generated by Django 4.2.7 on 2023-11-07 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("amyx_bank", "0006_alter_bankaccount_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="account",
        ),
        migrations.RemoveField(
            model_name="bankaccount",
            name="profile",
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
