# Generated by Django 4.2.7 on 2023-11-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amyx_bank", "0007_remove_bankaccount_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="balance",
            field=models.CharField(default=0, max_length=10),
        ),
    ]
