# Generated by Django 4.2.6 on 2023-10-31 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('amyx_bank', '0008_card_card_account_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='target_ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_obj', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
