# Generated by Django 4.2.6 on 2023-11-07 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_profile_user"),
        ("amyx_bank", "0008_card_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="balance",
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_accounts",
                to="account.profile",
            ),
        ),
    ]
