# Generated by Django 4.2.6 on 2023-11-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amyx_bank", "0009_remove_card_balance_alter_bankaccount_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="user",
        ),
        migrations.RemoveField(
            model_name="card",
            name="account",
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="profile",
            field=models.ManyToManyField(
                null=True, related_name="cards", to="amyx_bank.card"
            ),
        ),
    ]
