# Generated by Django 4.2.6 on 2023-11-02 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('amyx_bank', '0009_bankaccount_target_ct_bankaccount_target_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='deleted_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='target_ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_obj', to='contenttypes.contenttype'),
        ),
    ]
