# Generated by Django 4.2.6 on 2023-11-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amyx_bank", "0010_remove_bankaccount_user_remove_card_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="profile",
            field=models.ManyToManyField(related_name="cards", to="amyx_bank.card"),
        ),
    ]
