# Generated by Django 4.2.6 on 2023-11-02 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amyx_bank', '0010_deleted_user_transaction_alter_bankaccount_target_ct'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleted_user',
            name='deleted_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='deleted_user',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
