# Generated by Django 4.2.6 on 2023-11-04 13:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("amyx_bank", "0011_deleted_user_deleted_date_deleted_user_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bankaccount",
            options={"ordering": ["-account_code"]},
        ),
        migrations.AlterModelOptions(
            name="card",
            options={"ordering": ["-card_account_code"]},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["-user"]},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddField(
            model_name="card",
            name="target_ct",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cards",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="target_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="users/%Y/%m/%d/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="target_ct",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profiles",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="target_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name="transaction",
            name="concept",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="kind",
            field=models.CharField(default="buy", max_length=20),
        ),
        migrations.AddField(
            model_name="transaction",
            name="target_ct",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="target_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="target_ct",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bank_accounts",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["-account_code"], name="amyx_bank_b_account_21d153_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["target_ct", "target_id"], name="amyx_bank_b_target__9d7ea8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(
                fields=["-card_account_code"], name="amyx_bank_c_card_ac_71e9ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(
                fields=["target_ct", "target_id"], name="amyx_bank_c_target__88d38b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["-user"], name="amyx_bank_p_user_id_129130_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["target_ct", "target_id"], name="amyx_bank_p_target__e9295d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["-timestamp"], name="amyx_bank_t_timesta_e08404_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["target_ct", "target_id"], name="amyx_bank_t_target__7f4333_idx"
            ),
        ),
    ]
