# Generated by Django 4.2.6 on 2023-11-07 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("amyx_bank", "0011_alter_bankaccount_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="profile",
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cards",
                to="amyx_bank.bankaccount",
            ),
        ),
    ]
