# Generated by Django 4.2.6 on 2023-11-04 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("amyx_bank", "0013_alter_transaction_timestamp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
