# Generated by Django 4.2.6 on 2023-11-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amyx_bank", "0014_delete_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="status",
            field=models.CharField(
                choices=[("AC", "Active"), ("DS", "Disable"), ("CN", "Cancelled")],
                default="AC",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="status",
            field=models.CharField(
                choices=[("AC", "Active"), ("DS", "Disable"), ("CN", "Cancelled")],
                default="AC",
                max_length=20,
            ),
        ),
    ]
