# Generated by Django 4.2.7 on 2023-11-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amyx_bank', '0017_newprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewProfile',
        ),
    ]
