# Generated by Django 4.2.6 on 2023-11-08 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amyx_bank', '0001_initial'),
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='amyx_bank.bankaccount'),
        ),
    ]
