# Generated by Django 4.2.6 on 2023-11-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("card", "0003_alter_card_card_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="cvc",
            field=models.CharField(default="CVC", max_length=3),
        ),
        migrations.AlterField(
            model_name="card",
            name="card_name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
