# Generated by Django 4.2.6 on 2023-11-11 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="transaction",
            name="payment_tra_target__1243c8_idx",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="target_ct",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="target_id",
        ),
    ]
