# Generated by Django 4.2.6 on 2023-11-12 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_rename_account_balance_bankaccount_balance"),
        ("card", "0002_alter_card_options_and_more"),
        ("payment", "0002_remove_transaction_payment_tra_target__1243c8_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="account.bankaccount",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="kind",
            field=models.CharField(
                choices=[("OG", "OUTGOING"), ("IC", "INCOMING")],
                default="OG",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business", models.CharField(max_length=60)),
                ("concept", models.CharField(default="", max_length=100)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("kind", models.CharField(default="PAYMENTS", max_length=20)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="card.card"
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="payment_pay_timesta_bd99f9_idx"
                    )
                ],
            },
        ),
    ]
