# Generated by Django 4.2.6 on 2023-11-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_transaction_account_alter_transaction_kind_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.CharField(default="", max_length=7),
        ),
    ]
