# Generated by Django 4.2.8 on 2023-12-28 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_card_account'),
        ('payment', '0005_remove_payment_concept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='card.card'),
        ),
    ]
