# Generated by Django 4.2.6 on 2023-11-11 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bankaccount",
            old_name="account_balance",
            new_name="balance",
        ),
    ]
