# Generated by Django 4.2.7 on 2023-11-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(default='', max_length=50)),
                ('cvc', models.CharField(default='CVC', max_length=3)),
                ('card_account_code', models.CharField(blank=True, default='C5-0001', max_length=20)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('DS', 'Disable'), ('CN', 'Cancelled')], default='AC', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.bankaccount')),
            ],
            options={
                'ordering': ['-card_account_code'],
                'indexes': [models.Index(fields=['-card_account_code'], name='card_card_card_ac_40fc4a_idx')],
            },
        ),
    ]
