# Generated by Django 4.2.8 on 2023-12-28 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_bankaccount_profile'),
        ('card', '0002_alter_card_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='account.bankaccount'),
        ),
    ]
