# Generated by Django 4.2.10 on 2024-02-07 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_bankaccount_profile'),
        ('card', '0003_alter_card_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='account.bankaccount'),
        ),
    ]
